base_uri: https://ifcp.github.io/
labels:
  http://www.w3.org/2000/01/rdf-schema#label: 名称
  http://purl.org/NET/cidoc-crm/core#P3: 概要
  http://purl.org/NET/cidoc-crm/core#P4: 公開日
  http://purl.org/NET/cidoc-crm/core#P67: URL
  http://purl.org/NET/cidoc-crm/core#P141: 重要無形民俗文化財登録情報
  http://purl.org/NET/cidoc-crm/core#P94: 発祥情報
  http://purl.org/NET/cidoc-crm/core#P2: カテゴリー
site_title: Intangible Folk Cultural Properties
