base_uri: http://example.org/ifcp/
labels:
  http://www.w3.org/2000/01/rdf-schema#label: 名称
  http://purl.org/NET/cidoc-crm/core#P3: 概要
  http://purl.org/NET/cidoc-crm/core#P4: 公開日
  http://purl.org/NET/cidoc-crm/core#P67: URL
  http://purl.org/NET/cidoc-crm/core#P141: 重要無形民俗文化財登録情報
  http://purl.org/NET/cidoc-crm/core#P94: 発祥情報
  http://purl.org/NET/cidoc-crm/core#P31: 記入者
  http://purl.org/NET/cidoc-crm/core#P81: 発祥時期
  http://purl.org/NET/cidoc-crm/core#P107: 発祥地
  http://purl.org/NET/cidoc-crm/core#P2: カテゴリー
  http://www.w3.org/2004/02/skos/core#border: 上位カテゴリー
  http://www.w3.org/2004/02/skos/core#narrower: 下位カテゴリー
  http://purl.org/NET/cidoc-crm/core#P17: 開催情報
  http://purl.org/NET/cidoc-crm/core#P7: 開催地
  http://purl.org/NET/cidoc-crm/core#P14: 運営団体
  http://purl.org/NET/cidoc-crm/core#P116: 開始日
  http://purl.org/NET/cidoc-crm/core#P115: 終了日
site_title: Intangible Folk Cultural Properties
title_property: http://www.w3.org/1999/02/22-rdf-syntax-ns/#label
top_class: http://purl.org/NET/cidoc-crm/core#E1
